import { NextResponse } from "next/server";
import { sidebarConfig, SidebarItem } from "@/config/sidebar";
import { getAllDocSlugs, getDocBySlug } from "@/lib/docs";

// Enable CORS for IntelliJ plugin
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

export async function OPTIONS() {
  return NextResponse.json({}, { headers: corsHeaders });
}

/**
 * GET /api/docs
 * Returns the sidebar structure with titles resolved from translation keys
 */
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const locale = searchParams.get("locale") || "en";

  // For now, return a simplified structure with English titles
  // In production, you'd load these from the translation files
  const titleMap: Record<string, string> = {
    introduction: "Introduction",
    playerGuide: "Player Guide",
    overview: "Overview",
    beginnersGuide: "Beginner's Guide",
    faq: "FAQ",
    systemRequirements: "System Requirements",
    hytaleVsMinecraft: "Hytale vs Minecraft",
    knownIssues: "Known Issues",
    gettingStarted: "Getting Started",
    firstSteps: "First Steps",
    controls: "Controls",
    interface: "Interface",
    theWorld: "The World",
    worldZones: "World Zones",
    regions: "Regions",
    combat: "Combat",
    combatSystem: "Combat System",
    weapons: "Weapons",
    magic: "Magic",
    creatures: "Creatures",
    hostileCreatures: "Hostile Creatures",
    crafting: "Crafting",
    craftingGuide: "Crafting Guide",
    itemsDatabase: "Items Database",
    performanceOptimization: "Performance Optimization",
    devGettingStarted: "Developer Getting Started",
    prerequisites: "Prerequisites",
    environmentSetup: "Environment Setup",
    firstMod: "First Mod",
    firstModQuick: "Quick Start: First Mod",
    modding: "Modding",
    architecture: "Architecture",
    dataAssets: "Data Assets",
    blocks: "Blocks",
    properties: "Properties",
    behaviors: "Behaviors",
    items: "Items",
    npcs: "NPCs",
    aiSystem: "AI System",
    plugins: "Plugins",
    projectSetup: "Project Setup",
    pluginLifecycle: "Plugin Lifecycle",
    events: "Events",
    eventsOverview: "Events Overview",
    playerEvents: "Player Events",
    playerConnectEvent: "PlayerConnectEvent",
    playerDisconnectEvent: "PlayerDisconnectEvent",
    playerChatEvent: "PlayerChatEvent",
    playerSetupConnectEvent: "PlayerSetupConnectEvent",
    playerSetupDisconnectEvent: "PlayerSetupDisconnectEvent",
    playerReadyEvent: "PlayerReadyEvent",
    playerMouseButtonEvent: "PlayerMouseButtonEvent",
    playerMouseMotionEvent: "PlayerMouseMotionEvent",
    addPlayerToWorldEvent: "AddPlayerToWorldEvent",
    drainPlayerFromWorldEvent: "DrainPlayerFromWorldEvent",
    playerInteractEvent: "PlayerInteractEvent",
    playerCraftEvent: "PlayerCraftEvent",
    changeGameModeEvent: "ChangeGameModeEvent",
    blockEvents: "Block Events",
    breakBlockEvent: "BreakBlockEvent",
    placeBlockEvent: "PlaceBlockEvent",
    damageBlockEvent: "DamageBlockEvent",
    useBlockEvent: "UseBlockEvent",
    worldEvents: "World Events",
    addWorldEvent: "AddWorldEvent",
    removeWorldEvent: "RemoveWorldEvent",
    startWorldEvent: "StartWorldEvent",
    allWorldsLoadedEvent: "AllWorldsLoadedEvent",
    moonPhaseChangeEvent: "MoonPhaseChangeEvent",
    worldPathChangedEvent: "WorldPathChangedEvent",
    chunkEvents: "Chunk Events",
    serverEvents: "Server Events",
    bootEvent: "BootEvent",
    shutdownEvent: "ShutdownEvent",
    pluginSetupEvent: "PluginSetupEvent",
    entityEvents: "Entity Events",
    permissionEvents: "Permission Events",
    inventoryEvents: "Inventory Events",
    prefabEvents: "Prefab Events",
    damageEvents: "Damage Events",
    zoneEvents: "Zone Events",
    assetEvents: "Asset Events",
    npcEvents: "NPC Events",
    adventureEvents: "Adventure Events",
    i18nEvents: "i18n Events",
    singleplayerEvents: "Singleplayer Events",
    commands: "Commands",
    artAssets: "Art Assets",
    models: "Models",
    textures: "Textures",
    animations: "Animations",
    serverInternals: "Server Internals",
    serverInternalsOverview: "Overview",
    pluginSystem: "Plugin System",
    modules: "Modules",
    modulesOverview: "Modules Overview",
    entityStats: "Entity Stats",
    accessControl: "Access Control",
    damageSystem: "Damage System",
    interactions: "Interactions",
    timeSystem: "Time System",
    projectiles: "Projectiles",
    blockHealth: "Block Health",
    collisionSystem: "Collision System",
    staminaSystem: "Stamina System",
    prefabSystem: "Prefab System",
    entityUI: "Entity UI",
    effectsSystem: "Effects System",
    audioSystem: "Audio System",
    entitySpawning: "Entity Spawning",
    craftingSystem: "Crafting System",
    npcSystem: "NPC System",
    spawnSystem: "Spawn System",
    eventSystem: "Event System",
    commandSystem: "Command System",
    ecsSystem: "ECS System",
    dataTypes: "Data Types",
    networkPackets: "Network Packets",
    customUI: "Custom UI",
    uiReference: "UI Reference",
    officialApi: "Official API",
    endpoints: "Endpoints",
    authentication: "Authentication",
    sdks: "SDKs",
    javascript: "JavaScript",
    php: "PHP",
    servers: "Servers",
    networkProtocol: "Network Protocol",
    setup: "Setup",
    requirements: "Requirements",
    installation: "Installation",
    configuration: "Configuration",
    administration: "Administration",
    permissions: "Permissions",
    whitelist: "Whitelist",
    hosting: "Hosting",
    selfHosting: "Self-Hosting",
    budgetHosting: "Budget Hosting",
    docker: "Docker",
    cloudProviders: "Cloud Providers",
    tools: "Tools",
    blockbench: "Blockbench",
    pluginSetup: "Plugin Setup",
    modeling: "Modeling",
    animation: "Animation",
    assetEditor: "Asset Editor",
    editingData: "Editing Data",
    creativeMode: "Creative Mode",
    machinima: "Machinima",
    guides: "Guides",
    firstBlock: "First Block",
    firstItem: "First Item",
    firstNpc: "First NPC",
    customBiome: "Custom Biome",
    community: "Community",
    contributing: "Contributing",
    codeOfConduct: "Code of Conduct",
    resources: "Resources",
    mods: "Mods",
    communityServers: "Community Servers",
    contentCreators: "Content Creators",
    buildsGallery: "Builds Gallery",
    eventsCalendar: "Events Calendar",
  };

  function resolveTitle(key: string): string {
    return titleMap[key] || key;
  }

  function transformSidebar(items: SidebarItem[]): any[] {
    return items.map((item) => ({
      title: resolveTitle(item.titleKey),
      href: item.href || null,
      verified: item.verified || false,
      items: item.items ? transformSidebar(item.items) : undefined,
    }));
  }

  const sidebar = transformSidebar(sidebarConfig);

  return NextResponse.json(
    {
      sidebar,
      locale,
    },
    { headers: corsHeaders }
  );
}
